language: cpp

addons:
  apt:
    packages: rpm

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: BADGE=linux
    - os: osx
      compiler: clang
      env: BADGE=osx

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./src/cxmon ver  # print version
  - if test $TRAVIS_OS_NAME = linux ; then cpack ; fi # makes RPM
