language: cpp

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: BADGE=linux
    - os: osx
      compiler: clang
      env: BADGE=osx

script:
  - aclocal
  - autoconf
  - ./bootstrap
  - ./configure
  - make -j 4
  - make check
